import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });;

export const metadata = {
  title: "Nexus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />

        {/* Wrapper to contain background and content */}
        <div className="relative min-h-screen">
          <div className="absolute top-0 left-0 z-[-1] w-full h-full bg-[#000000] bg-[radial-gradient(#ffffff33_1px,#00091d_1px)] bg-[size:20px_20px]"></div>
          
          {/* Content inside the relative container */}
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
